name: key_board_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter


  # image get from camera
  image_picker: ^0.8.3
  camera: ^0.9.7+1
  # image to text
  google_ml_kit: ^0.11.0
  # pdf get from storage
  file_picker: ^4.5.1
  # architecture for state control
  flutter_bloc: ^8.0.1
  # language change
  easy_localization: ^3.0.0
  # to work with rest api
  http: ^0.13.4
  # to work with rest api
  http_parser: ^4.0.1
  # hive nosql database
  hive: ^2.1.0
  # for hive installation
  hive_flutter: ^1.1.0
  # speech to text maker
  speech_to_text: ^5.4.3
  # to extract sound in the program
  audioplayers: ^0.20.1
  # lottie animation icons
  lottie: ^1.3.0
  # animations
  simple_animations: ^4.0.1
  # get path from storage
  path_provider: ^2.0.10
  # internet checking
  connectivity_plus: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/sounds/



 # custom text fonds
#  fonts:
#    - family: Serif
#      fonts:
#        - asset: assets/fonts/AveriaSerifLibre-Regular.ttf
#        - asset: assets/fonts/AveriaSerifLibre-Bold.ttf
#        - asset: assets/fonts/AveriaSerifLibre-Italic.ttf
#        - asset: assets/fonts/AveriaSerifLibre-Light.ttf
